- hosts: all
  user: dementiev

  tasks:
  - name: Update apt cache
    become: yes
    apt:
     update_cache: yes

  - name: install required packages
    become: yes
    apt:
     name: "{{ packages }}"
    vars:
     packages:
     - mysql-client
     - nginx
     - python3-pip

  - name: Install Django
    become: yes
    pip: name=django version=1.11 state=present

  - name: Installing Django-CMS
    become: yes
    pip:
     name: "{{ packages }}"
    vars:
      packages:
      - django-cms

  - name: Create new django project
    command: django-admin startproject testwebapp

  - name: cp settings
    command: cp settings.py testwebapp/testwebapp/settings.py

  - name: cp urls
    command: cp urls.py testwebapp/testwebapp/urls.py

#  - lineinfile:
#     path: testwebapp/testwebapp/settings.py
#     line: 'from local_settings import *'

  - name: Configuring nginx
    become: yes
    template: src=nginx.j2 dest=/etc/nginx/sites-available/default

  - name: create symlink nginx config
    become: yes
    file: src=/etc/nginx/sites-available/default dest=/etc/nginx/sites-enabled/default state=link

  - name: restart nginx
    become: yes
    service:
     name: nginx
     state: restarted
